### ISSUE TITLE
Can I instal hibari on Debian latest version distro?

### ISSUE THREAD

**Issue by topstarnetwork** [hibari/hibari#42]
Can I instal hibari on Debian latest version distro?

**Comment by tatsuya6502** [comment]
> May I instal Hibari on Debian distro?

Thanks for your interest in Hibari. Yes, you may install Hibari on Debian. Hibari should run on any Unix-like operating systems including Linux destros (so far, tested on CentOS, Fedora and Ubuntu) and FreeBSD.

However, there are some notes:

- There is no binary package for Hibari so you need to install Erlang/OTP and then compile Hibari from source.
- The current stable release v0.1.10 is only compatible with Erlang/OTP R15. I'm right now working on v0.1.11 that is compatible with OTP 17. (GitHub issue: https://github.com/hibari/hibari/issues/41)

When v0.1.10 is released, I'll post an announcement to the mailing list.
http://groups.google.com/forum/#!forum/hibaridb-users

**Comment by topstarnetwork** [comment]
Thank you for this great news,
I had contacted you from github but got no answer from you.
So would you advise me to wate that your altest erlang otp version is
ready for production???

I also had another question, is Hibari more powerfull and has more
functionalities then compare to Riak????

Regards, Heather

**Comment by tatsuya6502** [comment]
Hi Heather,

> So would you advise me to wate that your altest erlang otp version is ready for production???

Hibari v0.1.10 is considered production-ready but it's only compatible with old Erlang/OTP R15. We have two large production clusters (~100 nodes) at a customer site: one is using R14B since 2010, another is using R15B since 2012. They are very stable.

I'm planning to release Hibari v0.1.11 in a week or so. It will be compatible with the latest Erlang/OTP 17.4.

> I also had another question, is Hibari more powerfull and has more functionalities then compare to Riak????

I'll answer this in another [GitHub issue #44](https://github.com/hibari/hibari/issues/44).

**Comment by topstarnetwork** [comment]
That is all great, all you do is anouncing me great positive vibe news,
I'll waite and then we can get started, thanks
