### ISSUE TITLE
Can I instal Hibari with MongooseIM ?

### ISSUE THREAD

**Issue by topstarnetwork** [hibari/hibari#43]
Can I instal Hibari with MongooseIM https://github.com/esl/MongooseIM    ?

**Comment by tatsuya6502** [comment]
I'm not familiar with MongooseIM so I need more time to look at the architecture and source code of this messaging product. But obviously MongooseIM doesn't support Hibari as the storage. It currently supports Mnesia and some RDBMS (MySQL, PostgreSQL).

I'm not sure how difficult to write an Hibari driver for MongooseIM, but it might be hard because Hibari's data structure is different form the ones in Mnesia and RDBMS. Hibari is a key-value store so each row has only one column and it doesn't support join operation between tables. Others are relational store so each row has many columns and support the join operation. Hibari can emulate table-like structure (each row has many columns) by using key-prefix and micro-transaction, but it still doesn't support join operation and transaction spanning multiple tables.

Let me check more about MongooseIM.

**Comment by topstarnetwork** [comment]
Well,
could you please check for wich paquage we should use in order to build a high traffic social network  website with a high load , high traffic mail server wich wil offer, telecom, mail hosting and jaber server messaging suite.
This platform will offer also a super market shopping cart with high load network layer resources.

As I am ingorant and no IT literate at all, please advise me,
the softwares I WAS THINKING STARTING WITH ARE AS FOLLOW:

1) http://www.rabbitmq.com/
2) Erlang otp latest edition
3) MongooseIM for messaging server
4) PostgreSQL
5) Mnesia
6) Hibari

Can all the above be packed and architected all together to create my social network and mail server platform?
Regards, Heather

**Comment by tatsuya6502** [comment]
I'm not quite sure if I understand your original question "Can I install Hibari with MongooseIM?"  If it means "Can I deploy Hibari on the same machine that has MongooseIM deployed?", my answer is "maybe yes". I'm not familiar with this product but I think it's mostly written in Erlang with a bit of C bindings. I don't see anything that would prevent Hibari to be deployed on the same machine.

But please note that you'll need more than one machines for deploying your platform because

1. For high availability, you need at least three machines for Hibari
2. Hibari v0.1.x demands large amount of available RAM so you probably
   don't want to deploy other software on the same machine
   * Hibari writes key-values to local disks but also keeps key
     part of key-values in memory. This is similar design to Riak's
     Bitcask backend. While this is good for performance, the amount
     of key-values that can be stored in Hibari is limited by
     available RAM.

As for 2, next major release of Hibari will have per-table option that lets you choose to keep keys in memory or not. If you choose the latter option, you'll get less performance but you can store far more
key-values in the table. If you need such feature for your application, please let me know. I'll put priority on the feature in such case.


> 1) http://www.rabbitmq.com/
> 2) Erlang otp latest edition
> 3) MongooseIM for messaging server
> 4) PostgreSQL
> 5) Mnesia
> 6) Hibari
>
> Can all the above be packed and architected all together to create my social network and mail server platform

Again, if "be packed" means they can be deployed to the same machine, then answer will be "maybe technically possible". But if you're building a platform that is capable to handle high-traffic and also
provides high availability, you might want to deploy them (RabbitMQ, MongooseIM, PostgreSQL, Hibari, your web application, and your mail server) on different machines.

**Comment by topstarnetwork** [comment]
Let me prepare my project softwares with plans and we'll talk about it together on how to architecture all these,
thanks

**Comment by tatsuya6502** [comment]
OK. When you tell me more details, please give me some idea which of these applications will use Hibari. This will help me to give you more concrete answers.

1. a high traffic social network website with a high load
2. high traffic mail server which will offer, telecom, mail hosting and jaber server messaging suite
3. a super market shopping cart with high load network layer resources

Thanks

**Comment by tatsuya6502** [comment]
Closing this for now. Please reopen when there is any update on the application architecture.
