### ISSUE TITLE
What is the difference between Hibari, mnesia  & Riak is a distributed NoSQL ?

### ISSUE THREAD

**Issue by topstarnetwork** [hibari/hibari#44]
What is the difference between Hibari, mnesia  & Riak is a distributed NoSQL ?
Does Hibari has suplementary features for telecom that mnesia  & Riak is a distributed NoSQL don't have?

**Comment by tatsuya6502** [comment]
Hibari was developed as the big-data storage for Gmail-like web-based mail service. That system is in production at a tier-1 telecom company since 2010.

Hibari has no fancy features, actually it has **far fewer features** than Mnesia and Riak do, but was carefully designed to meet non-functional requirements for typical telecom applications:

**Non-Functional Requirement for Typical Telecom Applications**

- NF1. **Low Latency, Predictable Latency, Read Optimized**: operations
  will complete in short time and latency is almost always
  predictable. Many NoSQL provides predictable latency for writes,
  but not for reads. Hibari provides it for both writes and reads by
  storing all keys in memory.
- NF2. **High Bandwidth**: provides high throughput by providing batch
  operation and lock-free mechanism
- NF3. **Big Data**: can store PB (Peta Bytes) of data by distributing
  data across servers
- NF4. **High Availability**: high fault tolerance by replicating data
  between servers
- NF5. **Stability**: can run years without restarting servers

**Functional Requirement for Web-Based Mail Storage**

- F6. **Sorted Keys**: keys are sorted by lexicographic order
- F7. **High Data Integrity**
   * a) **Always Guarantees Strong-Consistency**: prefer consistency
        over availability
   * b) **Compare and Swap (CAS)**: lock-free atomic operation (optimistic lock)
   * c) **Micro Transaction**: ACID transaction over key-values stored
        in single Hibari chain
- F8. **TTL (Time To Live) for Each Key-Value**
- F9. **Large Binary Value** (between few KB and few MB)


Unlike Mnesia and Riak, it deploys chain replication technique to realize above features. Chain replication is a simple but effective strategy to provide distributed store with strong consistency property. Because of this and having very small set of features, Hibari achieves higher performance and better stability than other distributed NoSQL products.

Of course, I'm biased, and others may disagree, but this is what I think:

- **Mnesia**
  * provides NF3, NF4, NF5, F6, F7-a and F7-c
  * doesn't provide F7-b and F8
  * didn't meet our requirements for NF1, NF2 and F9

- **Riak**
  * provides NF2, NF3, NF4, NF5 and F7-a
  * doesn't provides NF1, F6, F7-b, F7-c and F8
  * doesn't good at handling F9

**Features that Hibari (v0.1.10) doesn't provide:**

- **Mnesia** (4.12.4 in OTP 17.4)
  * RDB-like table structure (row has fixed number of columns).
    (Hibari is a key-value store)
  * complex objects (can store arbitrary Erlang term).
    (Hibari can only store binary data)
  * complex query language (qlc)
  * inter-table transaction
  * locking (pessimistic locking)
  * dirty operations for extra performance
  * secondary indexes

- **Riak** (2.0.5)
  * eventual consistency (prefer availability over consistency)
  * non-Erlang client support (Java, Ruby, Python, etc.)
  * rich data types (flags, registers, counters, sets, maps)
  * map/reduce
  * secondary indexes
  * pre/post commit hooks
  * Riak search (full text search)

- **Riak Enterprise** (2.0.5)
  * one-way asynchronous multi-datacenter replication
  * SNMP monitoring
  * JMX monitoring

**Comment by topstarnetwork** [comment]
Is there any way to emplement all the features that ; Mnesia (4.12.4 in OTP 17.4) and Riak (2.0.5) and Riak Enterprise (2.0.5) have onto Hibari?

**Comment by tatsuya6502** [comment]
No. Designing distributed database is all about choosing trade-offs. Mnesia, Riak and Hibari have very different fundamental design. So some features are totally impossible to implement. Some other features will be possible but they might take years to implement as I can spend only 1 or 2 hours a day on Hibari.

For example, it's impossible to implement Mnesia's "RDB-like table structure" and "inter-table transaction" on Hibari due to design differences. And by similar reason, it's impossible to implement Hibari's "compare and swap" on Riak.

But while "RDB-like table structure" is impossible, Hibari may have alternative ways to archive your application's goal. So I encourage you to breakdown your question into something more specific to your application.

For example:
- I want to store shopping cart. User can add/delete/list items, and my application displays number of items in the cart and total price on the screen. Also shopping cart need to be cleaned up after user session has expired. What will be the best data model for such data in Hibari? (how many tables do I need? what the row key and row-prefix will be?)
- I need to store product inventory and track items in stock. How can I prevent race conditions that will cause to over-sell products (sell more items than actually in stock)?
- I need users email addresses to be unique, how can I prevent users to register duplicate email addresses? 

(Do not post such usage questions to GitHub issues. Please use hibari-users mailing list.)
