### ISSUE TITLE
May I instal Hibari on Debian GNU/kFreeBSD distro?

### ISSUE THREAD

**Issue by topstarnetwork** [hibari/hibari#45]
May I instal Hibari on Debian GNU/kFreeBSD http://en.wikipedia.org/wiki/Debian_GNU/kFreeBSD distro?

**Comment by tatsuya6502** [comment]
I've never tired but Hibari would work on Debian GNU/kFreeBSD. You can try the instructions in the following URL to compile pre-released Hibari v0.1.11 on Debian GNU/kFreeBSD, and if you have any problem, copy-n-paste the error message here so I can check.

https://github.com/hibari/hibari/issues/40#issuecomment-76329641

Hibari was originally developed for CentOS and I modified its Makefile to support Ubuntu. I'm now using FreeBSD 10.1-RELEASE for developing Hibari. So I think there will be a good chance that it will compile without any problem.

**Comment by topstarnetwork** [comment]
In any case, for a high traffic social network website with telecom features, what distro would you suggest,
debian 7 or freebsd or GNU/kFreeBSD?
I was told debian is the best machine on earth but freebsd range are super high security featured, this is why we use freebsd based distros for firewall routers etc...

So which distro from the above would you advise?
Regards, Heather

**Comment by tatsuya6502** [comment]
I'm not an Unix specialist so this is just my two cents.

I think they only have subtle difference in these days in terms of performance, stability and security. I heard Debian is more popular in Europe and Red Hat Enterprise Linux/CentOS are more popular in the U.S. But I would say both are good, mature, well-supported destros and I think it's more like person's preference to choose a distro unless you need commercial support.

It seems a small number of Debian users are using Debian GNU/kFreeBSD for their front-end servers where they need more security. But I think this distro is a bit outdated and have very small user base. And again, choosing it is more like a matter of preference.

As for FreeBSD, I have a couple of engineer friends in Internet/cloud service providers, and they love FreeBSD for their servers because of stability and security features. But a problem is that it's hard to
find good FreeBSD engineers to hire. I also heard many appliance vendors choose FreeBSD because it's license is less restrictive than Linux's.

I use FreeBSD for my desktop PC not only for security features, but also for some advanced features like ZFS and DTrace.

But for your case, you don't have to be bothered by FreeBSD because you'll have less chance to find good/experienced engineers for it. So go with Debian. It will be a good choice.

**Comment by topstarnetwork** [comment]
Nice, I will definatly go with debian but will you be abel to give me the hibari debian paquage instal?
Regards, Heather

**Comment by tatsuya6502** [comment]
OK. Let me check how difficult it would be to create the Debian package. I filed https://github.com/hibari/hibari/issues/48 for this.

**Comment by topstarnetwork** [comment]
You're great!
Maybe this will bring luck in the future project, thanks
