### ISSUE TITLE
Is hibari still mantained as I see no further development sinds last year?

### ISSUE THREAD

**Issue by topstarnetwork** [hibari/hibari#46]
Is hibari still mantained as I see no further development sinds last year?

**Comment by tatsuya6502** [comment]
I would say Hibari already reached to a production-ready stage in year 2010 and is still maintained now, but development for new features is pretty much idle. The current developer is only me (@tatsuya6502).

Hibari was developed and open-sourced by the company I work at -- Cloudian, Inc., formerly Gemini Mobile Technologies, Inc. Hibari was originally developed as a distributed, in-memory low-latency database for social media, then was modified to be on-disk big-data storage for Gmail-like web-based mail service. The latter system went production at a tier-1 telecom company in year 2010. The larger cluster has about 100 nodes and it's been very stable for these days.

Although Hibari only has very basic features for storage and has some weakness in server resource usage and operation & management, the customer is happy with it and we never added features or tried to address these weaknesses.

When the company open-sourced Hibari in 2010, we decided not to spend the company's resource to maintain it. Since then, Hibari was maintained by my colleague for his personal project, and then, in year 2012, I took it over from him and I'm working in my spare time for adding small features and making enhancements. Because there is no strong demand for new features/enhancements from the community, I tends to put lower priority to Hibari development.

So, if there are some demands, I'll be happy to spend more time on Hibari. But also development won't be very fast as I only have limited time to spare.

I would encourage you to evaluate Hibari, and if you're happy with the current features, that will be fantastic. If not, please tell me what features you need, so that I can estimate how long it will take to
develop.

**Comment by topstarnetwork** [comment]
That sounds absolutly great, I will keep you posted with my projects needs wich you could supervise and see what other features should be developped in Hibari.
